const DataFilmList = [
    {
        id: 1,
        title: 'PHÙ THỦY TỐI THƯỢNG TRONG ĐA VŨ TRỤ HỖN LOẠN ',
        trailer: 'https://www.youtube.com/embed/nBNtRvpCmms',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/d/r/dr-strange-payoff-poster_1_.jpg',
        time: "04/05/2022" ,
        length: "126 phút",
        director: "Sam Raimi",
        actor: "Benedict Cumberbatch, Elizabeth Olsen Rachel McAdams", 
        category:   "Hành Động, Phiêu Lưu, Thần thoại",
        content: "Sau các sự kiện của Avengers: Endgame, Tiến sĩ Stephen Strange tiếp tục nghiên cứu về Viên đá Thời gian. Nhưng một người bạn cũ đã trở thành kẻ thù tìm cách tiêu diệt mọi phù thủy trên Trái đất, làm xáo trộn kế hoạch của Strange và cũng khiến anh ta mở ra một tội ác khôn lường."
    },
    {
        id: 2,
        title: 'HARRY POTTER VÀ HÒN ĐÁ PHÙ THỦY (RE-RUN)',
        trailer: 'https://www.youtube.com/embed/lzZ_Z1Sfczg',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/h/p/hp1.jpg',
        time:"20/05/2022",
        length: "152 phút",
        director:"Chris Columbus",
        actor:"Daniel Radcliffe, Rupert Grint, Emma Watson, Tom Felton",
        category:"Phiêu Lưu, Thần thoại",
        content:"Chuyển thể của phần đầu tiên của cuốn tiểu thuyết dành cho thiếu nhi nổi tiếng của tác giả J.K.Rowling, cậu bé Harry Potter vào sinh nhật lần thứ 11 rằng bố mẹ cậu là hai vị phù thủy nổi tiếng. Bản thân cậu sở hữu phép thuật và năng lực mà ai cũng mong muốn có được sau khi sống sót khỏi Chúa tể Voldermort. Từ cuộc sống của một đứa trẻ mồ côi, cậu trở thành một học sinh tại ngôi trường phù thủy danh giá Hogwarts. Tại đây, cậu đã tìm được những người bạn thân nhất của mình và giúp cậu khám phá ra sự thật về cái chết bí ẩn của cha mẹ mình."
    },
    {
        id: 3,
        title: 'MỒI CÁ MẬP',
        trailer: 'https://www.youtube.com/embed/4P0ViFNc8t4',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/s/h/shark_bait_-_poster_1_.jpg',
        time:"20/05/2022",
        length: "85 phút",
        director:"James Nunn",
        actor:"Holly Earl, Catherine Hannay, Jack Trueman",
        category:"Hành Động, Hồi hộp, Kinh Dị",
        content:"Một nhóm bạn quyết định tận hưởng ngày cuối tuần ở Mexico. Sau một đêm tiệc tùng trên bãi biển, họ quyết định trộm motor nước để tiếp tục cuộc vui. Tuy nhiên, cuộc vui đã trở thành bi kịch kinh hoàng khi một trong hai chiếc motor nước bị chìm. Một người bạn bị thương nặng, và đằng xa xuất hiện một đàn cá mập. Liệu nhóm bạn trẻ có thể thoát khỏi lưỡi hái của tử thần?"
    },
    {
        id: 4,
        title: 'NGHỀ SIÊU DỄ',
        trailer: 'https://www.youtube.com/embed/1anBxcsV5b8',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/r/s/rsz_nsd_main-poster.jpg',
        time:"29/04/2022",
        length: "113 phút",
        director:"Võ Thanh Hòa",
        actor:"Hứa Vĩ Văn, Thu Trang, Kiều Minh Tuấn, Tiến Luật, Huỳnh Phương, Quang Tuấn, Vũ Ngọc Anh, Thanh Mỹ",
        category:"Hài, Hành Động",
        content:'Ông Thái là một cảnh sát về hưu nhưng không chịu an phận thủ thường, hàng ngày vẫn đi tìm bắt tội phạm vặt trong xóm cho đỡ nhớ nghề. Một ngày kia, Hoàng - tên trùm ma túy mới ra tù bỗng dưng chuyển đến xóm ông và mở một văn phòng bất động sản. Nghi ngờ đây là nơi làm ăn phi pháp, ông Thái quyết định âm thầm điều tra. Ông mua lại tiệm cơm tấm đối diện trụ sở của Hoàng để làm nơi theo dõi, đồng thời thu nạp Thu - Phú - Vinh - Mèo, đám thanh niên “bất hảo” trong xóm về quán hỗ trợ buôn bán để rảnh tay "phá án". Trớ trêu thay, tiệm cơm bất ngờ nổi tiếng và ăn nên làm ra, khiến cho "chuyên án đặc biệt" của ông đứng trước nguy cơ đổ bể.'},
    {
        id: 5,
        title: 'DAENG – HẬU DUỆ “TÌNH NGƯỜI DUYÊN MA',
        trailer: 'https://www.youtube.com/embed/AseEmLs7RXE',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/1800x/71252117777b696995f01934522c402d/d/a/daeng_1080x1350_002_1_.jpg',
        time:"20/05/2022 ",
        length: "96 phút",
        director:"Watcharapong Pattama",
        actor:"Melik Efe Aigun, Maki-Machida Suthikul, Boat-Phuwarak Khamsing, MJ, Bikeweek-Surachai Borsuwan",
        category:"Kinh Dị",
        content:"Nối tiếp câu chuyện “Tình Người Duyên Ma” của nàng Nak - ma nữ nổi tiếng của người Thái với người chồng tên Mak, truyền thuyết cổ dựa trên những sự kiện lịch sử diễn ra từ thời vua Rama IV, Daeng là bộ phim kể về đứa bé ma do Nak sinh ra. Bộ phim xoay quanh cuộc sống của Daeng khi không có bố mẹ bên cạnh và tình bạn cũng như tình yêu với con người. Liệu cậu bé có được chào đón ở thế giới của con người hay phải đối diện với sự xa lánh, xua đuổi của dân làng như mẹ Nak?"},
    {
        id: 6,
        title: '578 PHÁT ĐẠN CỦA KẺ ĐIÊN',
        trailer: 'https://www.youtube.com/embed/TakNp0Iibt4',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/p/o/poster_578_1_.jpg',
        time:"20/05/2022",
        length: "106 phút",
        director:"Lương Đình Dũng",
        actor:"Minh Quang Nguyễn, Thanh Thảo, H’Hen Niê, Hoàng Phúc, Ngọc Tình, Tuấn “Hạc”, Jessica Minh Anh, Nguyễn Lâm Thảo Tâm, Hà Văn Hiếu ...",
        category:"Hành Động",
        content:"Hùng, một người cha sẵn sàng đánh đổi mọi thứ, thậm chí đặt mạng sống của mình vào hiểm nguy trong cuộc truy đuổi đơn độc nhưng vô cùng khốc liệt với kẻ ác để tìm lại công lý cho cô con gái bé nhỏ của mình. Nhưng điều anh không ngờ rằng phía sau kẻ ác đó lại là cả một thế lực ngầm …"},
    {
        id: 7,
        title: 'TĂNG TỐC.. VỀ PHÍA EM',
        trailer: 'https://www.youtube.com/embed/h261_whvLPM',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/r/s/rsz_1fast___feel_love_-_localized_poster_vn_-_revised.jpg',
        time:"29/04/2022",
        length: "131 phút",
        director:"Nawapol Thamrongrattanarit",
        actor:"Nat Kitcharit, Urassaya Sperbund, Anusara Korsamphan, Kanokwan Butrachart, Wipawee Patnasiri, Keetapat Pongruea",
        category:"Hài, Tình cảm",
        content:"Kao (Nat Kitcharit) là một nhà vô địch thế giới môn xếp ly tốc độ (Speed Stack). Tuy thành công và nổi tiếng nhưng Kao lại chỉ như một đứa trẻ to xác suốt ngày chỉ ăn, ngủ và tập luyện. Mọi vấn đề xung quanh anh đều một tay Jay (Yaya) bạn gái anh quán xuyến. Đến một ngày khi Jay quyết định chia tay thì Kao như bị mất tất cả. Anh phải bắt đầu học những kỹ năng sống cơ bản để có thể tự sống một mình và chăm sóc bản thân. Song song đó những đối thủ mới cũng xuất hiện và đe dọa đến vị trí quán quân của Kao."},
    {
        id: 8,
        title: 'THỎ GÀ RÀ KHO BÁU',
        trailer: 'https://www.youtube.com/embed/45x7W907TBg',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/c/h/chickenhare-_vietnamese_poster_1_.jpg',
        time:"29/04/2022",
        length: "92 phút",
        director:"Ben Stassen, Benjamin Mousquet",
        actor:"Danny Fehsenfeld, Joe Ochman",
        category:"Hoạt Hình, Phiêu Lưu",
        content:"Bộ phim theo chân cuộc phiêu lưu của Chickenhare, vị anh hùng trẻ tuổi sinh ra là nửa thỏ rừng nửa gà, được Vua Peter- một nhà thám hiểm thỏ rừng nổi tiếng nhận nuôi. Chickenhare luôn háo hức với những chuyến phiêu lưu, và mong muốn được yêu thương mặc cho những khác biệt của mình. Khi kẻ phản diện sừng sỏ nhất của vương quốc, cũng chính là cậu của Chickenhare trốn khỏi ngục và đe dọa lật đổ cha mình, Chickenhare dấn thân vào một cuộc đua kỳ thú cùng với Abe- chú rùa thích châm chọc, và Meg- nữ chuyên gia võ thuật liều lĩnh nhằm ngăn chặn âm mưu của cậu mình."},
    {
        id: 9,
        title: 'KẺ THỨ BA',
        trailer: 'https://www.youtube.com/embed/I0AVVZx0O3o',
        imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/1/image/1800x/71252117777b696995f01934522c402d/p/o/poster-ke-thu-3_1_.jpg',
        time:"13/05/2022",
        length: "87 phút",
        director:"Park Hee Jun",
        actor:"Han Jae Suk, Lý Nhã Kỳ",
        category:"Tâm Lý, Tình cảm",
        content:"Kẻ Thứ Ba là câu chuyện về Thiên Di (diễn viên Lý Nhã Kỳ), một nữ bác sĩ bạc mệnh qua đời trong một vụ tai nạn giao thông. Dù đã ra đi hơn một năm nhưng Thiên Di vẫn để lại cho chồng cô, họa sĩ Quang Kha (nam tài tử xứ Hàn Han Jae Suk thủ vai) nỗi đau khôn xiết cùng những hoài niệm về tháng ngày hạnh phúc. Vô tình Quang Kha mua được một chiếc laptop có thể liên lạc được về quá khứ của một nữ VJ nổi tiếng (diễn viên Kim Tuyến). Quang Kha tìm cách nhờ nữ VJ cứu vợ khỏi cuộc tai nạn năm xưa, đổi lại anh cho cô biết dãy số trúng độc đắc Vietlott giải thưởng hơn trăm tỉ… Khi nữ VJ nhận lời giúp đỡ Quang Kha là lúc vòng xoáy của những âm mưu, tội ác và cả những cú twist liên tục được hé lộ, lôi cuốn khán giả đi từ bất ngờ này đến bất ngờ khác. Kẻ thứ ba, thậm chí là Kẻ thứ tư bất ngờ lộ diện, ai cũng có lý do với những mưu cầu cá nhân khiến câu chuyện trở nên kịch tính, khó đoán định. Kẻ Thứ Ba do diễn viên Lý Nhã Kỳ sản xuất trở thành bữa tiệc cuốn hút khác lạ của điện ảnh Việt bởi những drama, tình tiết lôi cuốn được ra rạp từ 13.5.2022."}
]

export default DataFilmList